name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ["16", "18", "20", "21"]

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-cqnqk3lsvqrc73fqh1d0 \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
